<?php
require_once 'auth_check.php'; require_once '../koneksi.php'; require_once 'app_helpers.php';
$role=$_SESSION['kode_role'];
if(!in_array($role,['ADMIN','OPERATOR_PRODI'],true)){http_response_code(403);die('403 - Akses ditolak.');}
$q=trim($_GET['q']??''); $status=$_GET['status']??'';
$where=[];$params=[];$types='';
if($role==='OPERATOR_PRODI'){ $where[]='m.id_program_studi = ?'; $params[]=(int)$_SESSION['id_program_studi']; $types.='i'; }
if($q!==''){ $where[]='(m.npm LIKE ? OR m.nama_mahasiswa LIKE ?)'; $like="%$q%";$params[]=$like;$params[]=$like;$types.='ss'; }
if($status!==''){ $where[]='m.status_mahasiswa = ?'; $params[]=$status;$types.='s'; }
$sql="SELECT m.*,ps.nama_program_studi,f.nama_fakultas FROM mahasiswa m JOIN program_studi ps ON m.id_program_studi=ps.id_program_studi JOIN fakultas f ON ps.id_fakultas=f.id_fakultas".(count($where)?' WHERE '.implode(' AND ',$where):'')." ORDER BY m.id_mahasiswa DESC";
$stmt=mysqli_prepare($koneksi,$sql); if($params) mysqli_stmt_bind_param($stmt,$types,...$params); mysqli_stmt_execute($stmt); $result=mysqli_stmt_get_result($stmt);
$canAdd=in_array($role,['ADMIN','OPERATOR_PRODI'],true);
?><!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Data Mahasiswa</title><link rel="stylesheet" href="style.css"></head><body class="app-body">
<?php include 'topbar.php'; include 'sideleftbar.php'; ?><main class="main-content">
<div class="page-heading page-heading-flex"><div><span class="eyebrow">DATA AKADEMIK</span><h1>Data Mahasiswa</h1><p>Kelola data mahasiswa sesuai kewenangan akun.</p></div><?php if($canAdd): ?><a class="btn btn-primary" href="mahasiswa_tambah.php">+ Tambah Mahasiswa</a><?php endif;?></div>
<?php flash_html(); ?><div class="dashboard-panel"><div class="toolbar"><form class="search-form" method="get"><input name="q" value="<?=e($q)?>" placeholder="Cari NPM atau nama mahasiswa..."><select name="status"><option value="">Semua status</option><?php foreach(['Aktif','Cuti','Lulus','Mengundurkan Diri','Drop Out','Tidak Aktif'] as $s):?><option value="<?=e($s)?>" <?=$status===$s?'selected':''?>><?=e($s)?></option><?php endforeach;?></select><button class="btn btn-primary" type="submit">Cari</button><?php if($q||$status):?><a class="btn btn-outline" href="mahasiswa.php">Reset</a><?php endif;?></form></div>
<div class="table-responsive"><table class="data-table"><thead><tr><th>No</th><th>NPM</th><th>Nama</th><th>Prodi</th><th>JK</th><th>Status</th><th>Aksi</th></tr></thead><tbody><?php $no=1;while($r=mysqli_fetch_assoc($result)): ?><tr><td><?=$no++?></td><td><strong><?=e($r['npm'])?></strong></td><td><?=e($r['nama_mahasiswa'])?></td><td><?=e($r['nama_program_studi'])?></td><td><?=$r['jenis_kelamin']==='L'?'Laki-laki':'Perempuan'?></td><td><span class="badge <?=in_array($r['status_mahasiswa'],['Aktif','Lulus'],true)?'':'badge-warning'?>"><?=e($r['status_mahasiswa'])?></span></td><td><div class="action-group"><a class="btn btn-sm btn-outline" href="mahasiswa_detail.php?id=<?=$r['id_mahasiswa']?>">Detail</a><?php if($canAdd):?><a class="btn btn-sm btn-outline" href="mahasiswa_edit.php?id=<?=$r['id_mahasiswa']?>">Edit</a><form method="post" action="mahasiswa_hapus.php" onsubmit="return confirm('Hapus data mahasiswa ini?');"><input type="hidden" name="id" value="<?=$r['id_mahasiswa']?>"><?=csrf_field()?><button class="btn btn-sm btn-danger">Hapus</button></form><?php endif;?></div></td></tr><?php endwhile;if(mysqli_num_rows($result)===0):?><tr><td colspan="7" class="empty-state">Data mahasiswa tidak ditemukan.</td></tr><?php endif;?></tbody></table></div></div></main><script src="script.js"></script></body></html>